config/routes.rb
Rails.application.routes.draw do

  resources :appointments
  #resources :users

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/failure'

  get 'site/index'
  get 'site/salons'

  #Omniauth Routes
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  post '/signout' => 'sessions#destroy', :as => :signout

  resources :salons do #, param: :name
    resources :products
    resources :salon_images
  end

  root 'salons#index'

end

app/models/salon_image.rb
class SalonImage < ApplicationRecord
  belongs_to :salon
  attr_accessor :image_file
  validates_presence_of :image_file

  PREVIEW_LIST_LIMIT = 6

  private 
  after_create :upload_image

  def upload_image
    image = StorageBucket.files.new(
      key: "salon_images/#{id}/#{image_file.original_filename}",
      body: image_file.read,
      public: true
    )

    image.save
    update_columns image_url: image.public_url
  end

  before_destroy :delete_image, if: :image_url

  def delete_image
    bucket_name = StorageBucket.key
    image_uri   = URI.parse image_url

    if image_uri.host == "#{bucket_name}.storage.googleapis.com"
      # Remove leading forward slash from image path
      # The result will be the image key, eg. "images/:id/:filename"
      image_key = image_uri.path.sub("/", "")
      image     = StorageBucket.files.new key: image_key

      image.destroy
    end
  end

  before_update :update_image, if: :image_file
  
  def update_image
    delete_image if image_url?
    upload_image
  end

end

app/controllers/salon_images_controller.rb
class SalonImagesController < ApplicationController
  before_action :set_salon_image, only: [:show, :edit, :update, :destroy]
  before_action :set_parent_salon, only: [:index, :new, :show, :edit, :update, :destroy, :create]
  layout 'admin'

  # GET /salon_images
  # GET /salon_images.json
  def index
    @salon_images = @salon.salon_images.all
  end

  # GET /salon_images/1
  # GET /salon_images/1.json
  def show
  end

  # GET /salon_images/new
  def new
    @salon_image = SalonImage.new
  end

  # GET /salon_images/1/edit
  def edit
  end

  # POST /salon_images
  # POST /salon_images.json
  def create
    @salon_image = @salon.salon_images.new(salon_image_params)

    respond_to do |format|
      if @salon_image.save
        format.html { redirect_to salon_salon_image_path(@salon, @salon_image), notice: 'Salon image was successfully created.' }
        format.json { render :show, status: :created, location: @salon_image }
      else
        format.html { render :new }
        format.json { render json: @salon_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salon_images/1
  # PATCH/PUT /salon_images/1.json
  def update
    respond_to do |format|
      if @salon_image.update(salon_image_params)
        format.html { redirect_to salon_salon_image_url(@salon, @salon_image), notice: 'Salon image was successfully updated.' }
        format.json { render :show, status: :ok, location: @salon_image }
      else
        format.html { render :edit }
        format.json { render json: @salon_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salon_images/1
  # DELETE /salon_images/1.json
  def destroy
    @salon_image.destroy
    respond_to do |format|
      format.html { redirect_to salon_salon_images_url(@salon), notice: 'Salon image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salon_image
      @salon_image = SalonImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salon_image_params
      params.require(:salon_image).permit(:name, :image_file, :type)
    end
end

app/helpers/salon_images_helper.rb
module SalonImagesHelper
end

app/views/salon_images/_form.html.erb
<%= form_for([@salon, salon_image], html:{multipart:true}) do |f| %>
  <% if salon_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salon_image.errors.count, "error") %> prohibited this salon_image from being saved:</h2>

      <ul>
      <% salon_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image_file, class:"form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.label :type %>
    <%= f.number_field :type, class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
<br/>

app/views/salon_images/edit.html.erb
<h1>Editing Salon Image</h1>

<%= render 'form', salon_image: @salon_image %>

<%= link_to 'Show', salon_salon_image_path(@salon, @salon_image) %> |
<%= link_to 'Back', salon_salon_images_path(@salon) %>

app/views/salon_images/index.html.erb
<h2 class="sub-header">Image Management (<%= @salon.name %>)</h2>
<div class="table-responsive">
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salon_images.each do |salon_image| %>
      <tr>
        <td><%= salon_image.name %></td>
        <td><%= image_tag salon_image.image_url, class: "img-thumbnail" %></td>
        <td><%= salon_image.type %></td>
        <td><%= link_to 'Show', salon_salon_image_url(@salon, salon_image) %></td>
        <td><%= link_to 'Edit', edit_salon_salon_image_path(@salon, salon_image) %></td>
        <td><%= link_to 'Destroy', salon_salon_image_path(@salon, salon_image), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Salon Image', new_salon_salon_image_path(@salon) %>
<br />
<%= link_to "Back to Salon", salon_path(@salon) %>
</div>

app/views/salon_images/new.html.erb
<h1>New Salon Image</h1>

<%= render 'form', salon_image: @salon_image %>

<%= link_to 'Salon Edit', edit_salon_path(@salon.id) %> |
<%= link_to 'All Images', salon_salon_images_path(@salon.id) %>

app/views/salon_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @salon_image.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag @salon_image.image_url, class: "img-thumbnail", size:"500" %>
</p>

<p>
  <strong>Type:</strong>
  <%= @salon_image.type %>
</p>

<%= link_to 'Edit', edit_salon_salon_image_path(@salon, @salon_image) %> |
<%= link_to 'All Images', salon_salon_images_path(@salon) %>