config/routes.rb
Rails.application.routes.draw do

  resources :appointments
  #resources :users

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/failure'

  get 'site/index'
  get 'site/salons'

  #Omniauth Routes
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  post '/signout' => 'sessions#destroy', :as => :signout

  resources :salons do #, param: :name
    resources :products
    resources :salon_images
  end

  root 'salons#index'

end

app/views/shared/_admin_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% title = signed_in? ? "Salon Box (#{current_user.name})" : "Salon Box (Admin)" %>
      <%= link_to title, salons_path, class: "navbar-brand" %>
    </div>
    
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
        <li><%= link_to "Logout", signout_path, method:"post", data: { confirm: "Are you sure?" } %></li>
        <% else %> 
        <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
    </div>
    
  </div>  
</nav>