config/routes.rb
Rails.application.routes.draw do

  resources :appointments
  #resources :users

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/failure'

  get 'site/index'
  get 'site/salons'

  #Omniauth Routes
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  post '/signout' => 'sessions#destroy', :as => :signout

  resources :salons do #, param: :name
    resources :products
    resources :salon_images
  end

  root 'salons#index'

end

app/models/salon.rb
class Salon < ApplicationRecord
  has_many :products 
  has_many :salon_images

  validates_presence_of :name, :categories, :payment_options, :specialities

  CATEGORIES = %w(hair nails brow)
  AMENITIES = %w(wifi complimentary\ drinks parking food\ menu\ available drink\ menu\ available)
  KEY_PRODUCTS = %w(l'oreal\ professional kerastase makarizo shiseido)
  AMBIENCE = %w(welcoming cozy modern clean friendly personal)
  SPECIALITIES = %w(highlights japanese\ straightening haircut color hair\ treatment blowouts)
  PAYMENT_OPTIONS = %w(cash\ only credit\ card debit\ card)
  PLACEHOLDER_IMAGE = "placeholder.png"

  attr_accessor :main_image

  def display_image
    main_image_url.nil? ? PLACEHOLDER_IMAGE : main_image_url
  end

  private 
  after_create :upload_image, if: :main_image

  def upload_image
    image = StorageBucket.files.new(
      key: "salon_main_images/#{id}/#{main_image.original_filename}",
      body: main_image.read,
      public: true
    )

    image.save
    update_columns main_image_url: image.public_url
  end

  before_destroy :delete_image, if: :main_image_url

  def delete_image
    bucket_name = StorageBucket.key
    image_uri   = URI.parse main_image_url

    if image_uri.host == "#{bucket_name}.storage.googleapis.com"
      # Remove leading forward slash from image path
      # The result will be the image key, eg. "main_images/:id/:filename"
      image_key = image_uri.path.sub("/", "")
      image     = StorageBucket.files.new key: image_key

      image.destroy
    end
  end

  before_update :update_image, if: :main_image
  
  def update_image
    delete_image if main_image_url?
    upload_image
  end

end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  before_action :set_salon, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /salons
  # GET /salons.json
  def index
    @salons = Salon.all
  end

  # GET /salons/1
  # GET /salons/1.json
  def show
  end

  # GET /salons/new
  def new
    @salon = Salon.new
  end

  # GET /salons/1/edit
  def edit
  end

  # POST /salons
  # POST /salons.json
  def create
    @salon = Salon.new(salon_params)

    respond_to do |format|
      if @salon.save
        format.html { redirect_to @salon, notice: 'Salon was successfully created.' }
        format.json { render :show, status: :created, location: @salon }
      else
        format.html { render :new }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salons/1
  # PATCH/PUT /salons/1.json
  def update
    respond_to do |format|
      if @salon.update(salon_params)
        format.html { redirect_to @salon, notice: 'Salon was successfully updated.' }
        format.json { render :show, status: :ok, location: @salon }
      else
        format.html { render :edit }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salons/1
  # DELETE /salons/1.json
  def destroy
    @salon.destroy
    respond_to do |format|
      format.html { redirect_to salons_url, notice: 'Salon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salon
      @salon = Salon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salon_params
      params.require(:salon).permit(:name, :main_image, :description, :location, :active, :listed, :amenities => [], :key_product_list => [], :specialities => [], :payment_options => [], :categories => [], :services => [], :ambience => [])
    end
end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/views/salons/_form.html.erb
<%= form_for(salon, html:{class:"form", multipart:true}) do |f| %>
  <% if salon.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(salon.errors.count, "error") %> prohibited this salon from being saved:</h2>
    <ul>
      <% salon.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :main_image %>
    <%= f.file_field :main_image, class:"form-control-file" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class:"form-control", rows:"3" %>
  </div>

  <div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class:"form-control" %>
  </div>

  <hr />

  <%= f.label :categories %>
  <div class="form-check form-check-inline">
  <% Salon::CATEGORIES.each do |k| %>
    <label class="form-check-label">
      <%= f.check_box :categories, {multiple:true}, k, nil %>
      <%= k.titleize %>
    </label>
    <br/>
    <% end %>
  </div>

  <hr/ >

  <%= f.label :amenities %>
  <div class="form-check form-check-inline">
  <% Salon::AMENITIES.each do |k| %>
    <label class="form-check-label">
      <%= f.check_box :amenities, {multiple:true}, k, nil %>
      <%= k.titleize %>
    </label>
    <br/>
    <% end %>
  </div>

  <hr/ >

  <%= f.label :key_products %>
  <div class="form-check form-check-inline">
  <% Salon::KEY_PRODUCTS.each do |k| %>
    <label class="form-check-label">
      <%= f.check_box :key_product_list, {multiple:true}, k, nil %>
      <%= k.titleize %>
    </label>
    <br/>
    <% end %>
  </div>

  <hr/ >

  <%= f.label :ambience %>
  <div class="form-check form-check-inline">
  <% Salon::AMBIENCE.each do |k| %>
    <label class="form-check-label">
      <%= f.check_box :ambience, {multiple:true}, k, nil %>
      <%= k.titleize %>
    </label>
    <br/>
    <% end %>
  </div>
  <hr/ >

  <%= f.label :specialities %>
  <div class="form-check form-check-inline">
  <% Salon::SPECIALITIES.each do |k| %>
    <label class="form-check-label">
      <%= f.check_box :specialities, {multiple:true}, k, nil %>
      <%= k.titleize %>
    </label>
    <br/>
    <% end %>
  </div>
  <hr/ >

  <%= f.label :payment_options %>
  <div class="form-check form-check-inline">
  <% Salon::PAYMENT_OPTIONS.each do |k| %>
    <label class="form-check-label">
      <%= f.check_box :payment_options, {multiple:true}, k, nil %>
      <%= k.titleize %>
    </label>
    <% end %>
  </div>
  <hr/ >

    <% unless @salon.new_record? %>
    <ul class="list-group">
      <li class="list-group-item justify-content-between">
        <%= link_to "Add", new_salon_product_path(@salon.id), :class => "btn btn-primary" %> |
        <%= link_to "View All Menu Items (#{@salon.products.count})", salon_products_path(@salon.id) %>
      </li>
      <% if @salon.products.count > 0 %>
      <li class="list-group-item justify-content-between">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th>Price</th>
            </tr>
          </thead>
          <% @salon.products.limit(Product::PREVIEW_LIST_LIMIT).each do |product| %>

          <tbody>
            <tr>
              <td><%= product.name %></td>
              <td><%= product.price %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
      </li>
        <% end %>

      </li>
      <li class="list-group-item justify-content-between">
        <%= link_to "Add", new_salon_salon_image_path(@salon.id), :class => "btn btn-primary" %> |
        <%= link_to "View All Portfolio Images (#{@salon.salon_images.count})", salon_salon_images_path(@salon.id) %>
      </li>
      <li class="list-group-item justify-content-between">
        <div class="row">
          <% @salon.salon_images.limit(SalonImage::PREVIEW_LIST_LIMIT).each do |image| %>
          <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <%= image_tag image.image_url, class: "img-responsive" %>
          </div>
          <% end %>
        </div>
      </li>
    </ul>
    <% end %>
    <hr />

  <div class="form-check">
    <label class="form-check-label">
      <%= f.check_box :active, class:"form-check-input" %>
      Active
    </label>
  </div>

  <div class="form-check">
    <label class="form-check-label">
      <%= f.check_box :listed, class:"form-check-input" %>
      Listed
    </label>
  </div>
  <hr />
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
  <br>
<% end %>

app/views/salons/_list_item.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><%= col_name %></div>
  <ul class="list-group">
    <% col.each do |item| %>
    <li class="list-group-item"><%= item.titleize %></li>
    <% end %>
  </ul>
</div>

app/views/salons/_salon_list_card.html.erb
<div class="card mb-3">
  <%= image_tag "/sample_salon_images/salon_#{(1..5).to_a.sample}.jpg", class: "card-img-top" %>
  <div class="card-block">
    <h4 class="card-title"><%= salon.name %></h4>
    <p class="card-text"><%= salon.description %></p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
</div>

app/views/salons/edit.html.erb
<h1>Editing Salon</h1>

<%= render 'form', salon: @salon %>

<%= link_to 'Show', @salon %> |
<%= link_to 'Back', salons_path %>

app/views/salons/index.html.erb
<h2 class="sub-header">Salon Management</h2>
<div class="table-responsive">
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Main image</th>
      <th>Description</th>
      <th>Menu Items</th>
      <th>Portfolio Images</th>
      <th>Active</th>
      <th>Listed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salons.each do |salon| %>
      <tr>
        <td><%= salon.name %></td>
          <td><%= image_tag salon.display_image, class: "img-thumbnail", size:"500" %></td>
        <td><%= salon.description %></td>

        <td><%= link_to "Count: #{salon.products.count}", salon_products_path(salon) %></td>
        <td><%= link_to "Count: #{salon.salon_images.count}", salon_salon_images_path(salon) %></td>

        <td><%= salon.active %></td>
        <td><%= salon.listed %></td>
        <td><%= link_to 'Show', salon %></td>
        <td><%= link_to 'Edit', edit_salon_path(salon) %></td>
        <td><%= link_to 'Destroy', salon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Salon', new_salon_path %>
</div>

app/views/salons/new.html.erb
<h1>New Salon</h1>

<%= render 'form', salon: @salon %>

<%= link_to 'Back', salons_path %>

app/views/salons/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row form-group">
  <div class="col-xs-12 col-md-6">
    <div class="panel panel-default">
      <div class="panel-image">
        <%= image_tag @salon.display_image, class: "panel-image-preview" %>
      </div>
      <div class="panel-body">
        <h4><%= @salon.name %></h4>
        <p><%= @salon.description %></p>
      </div>
      <% if false %>
      <div class="panel-footer text-center">
        <a href="#facebook"><span class="fa fa-facebook"></span></a>
        <a href="#twitter"><span class="fa fa-twitter"></span></a>
      </div>
      <% end %>
    </div>
  </div>

  <div class="col-xs-12 col-md-6">
    <% if @salon.salon_images.count > 0 %>
    <div class="page-header">Portfolio Images -- <%= link_to "View All (#{@salon.salon_images.count})", salon_salon_images_path(@salon.id) %></div>

    <div class="row">
      <% @salon.salon_images.limit(SalonImage::PREVIEW_LIST_LIMIT).each do |image| %>
      <div class="col-lg-3 col-md-4 col-xs-6 thumb">
        <%= image_tag image.image_url, class: "img-responsive" %>
      </div>
      <% end %>
    </div>
    <hr />
    <% end %>
    
    <% if @salon.products.count > 0 %>
    <div class="page-header">Menu Items -- <%= link_to "View All (#{@salon.products.count})", salon_products_path(@salon.id) %> </div>
    <li class="list-group-item justify-content-between">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Price</th>
          </tr>
        </thead>
        <% @salon.products.limit(Product::PREVIEW_LIST_LIMIT).each do |product| %>
        
        <tbody>
          <tr>
            <td><%= product.name %></td>
            <td><%= product.price %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </li>
    <% end %>
  </div>
  
</div>

<div>
  <%= render partial: "list_item", locals: {col_name: "Categories", col: @salon.categories} if @salon.categories %>
  
  <%= render partial: "list_item", locals: {col_name: "Amenities", col: @salon.amenities} if @salon.amenities %>
  
  <%= render partial: "list_item", locals: {col_name: "Key Products", col: @salon.key_product_list}  if @salon.key_product_list %>
  
  <%= render partial: "list_item", locals: {col_name: "Ambience", col: @salon.ambience} if @salon.ambience %>
  
  <%= render partial: "list_item", locals: {col_name: "Specialities", col: @salon.specialities} if @salon.specialities %>
  
  <%= render partial: "list_item", locals: {col_name: "Payment Options", col: @salon.payment_options} if @salon.payment_options %>
  
  
  <p>
    <strong>Active:</strong>
    <%= @salon.active %>
  </p>
  
  <p>
    <strong>Listed:</strong>
    <%= @salon.listed %>
  </p>
  
  <%= link_to 'Edit', edit_salon_path(@salon) %> |
  <%= link_to 'Back', salons_path %>
</div>