config/routes.rb
Rails.application.routes.draw do

  resources :appointments
  #resources :users

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/failure'

  get 'site/index'
  get 'site/salons'

  #Omniauth Routes
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  post '/signout' => 'sessions#destroy', :as => :signout

  resources :salons do #, param: :name
    resources :products
    resources :salon_images
  end

  root 'salons#index'

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :salon
  validates_presence_of :name, :price

  PREVIEW_LIST_LIMIT = 5

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_parent_salon, only: [:index, :new, :show, :edit, :update, :destroy, :create]
  layout "admin"

  # GET /products
  # GET /products.json
  def index
    @products = @salon.products.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = @salon.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to salon_product_path(@salon, @product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to salon_product_path(@salon, @product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to salon_products_url(@salon), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description, :type, :salon_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for([@salon, product]) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :type %>
    <%= f.number_field :type, class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<br />
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', salon_product_path(@salon, @product) %> |
<%= link_to 'Back', salon_products_path(@salon) %>

app/views/products/index.html.erb
<h2 class="sub-header">Product Management (<%= @salon.name %>)</h2>
<div class="table-responsive">
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= product.type %></td>
        <td><%= link_to 'Show', salon_product_path(@salon, product) %></td>
        <td><%= link_to 'Edit', edit_salon_product_path(@salon,product) %></td>
        <td><%= link_to 'Destroy', salon_product_path(@salon,product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Product', new_salon_product_path(@salon) %>
<br />
<%= link_to "Back to Salon", salon_path(@salon) %>
</div>

app/views/products/new.html.erb
<h1>Add Product for: <%= @salon.name %></h1>

<%= render 'form', product: @product %>

<%= link_to 'Salon Edit', edit_salon_path(@salon.id) %> |
<%= link_to 'All Products', salon_products_path(@salon.id) %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @product.type %>
</p>

<p>
  <strong>Salon:</strong>
  <%= @product.salon_id %>
</p>

<%= link_to 'Edit', edit_salon_product_path(@salon,@product) %> |
<%= link_to 'All Products', salon_products_path(@salon.id) %>